services:
  wud:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped
    ports:
      - 3333:3000
    environment:
      WUD_LOG_LEVEL: warn
      # Watcher - Docker local
      WUD_WATCHER_LOCAL_SOCKET: /var/run/docker.sock
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: true
      # Trigger ntfy (priority: 1=min, 2=low, 3=default, 4=high, 5=max)
      WUD_TRIGGER_NTFY_HOMELAB_URL: http://192.168.1.20:5684
      WUD_TRIGGER_NTFY_HOMELAB_TOPIC: docker-updates
      WUD_TRIGGER_NTFY_HOMELAB_PRIORITY: 3
      WUD_TRIGGER_NTFY_HOMELAB_AUTH_TOKEN: ${WUD_TRIGGER_NTFY_HOMELAB_AUTH_TOKEN}
      WUD_WATCHER_LOCAL_INTERVAL: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/store
networks: {}
