services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - /mnt/externaldisk0/n8n/n8n_data:/home/node/.n8n
      - /home/jaumoso/selfhosted/n8n/local-files:/files
    extra_hosts:
      - host.docker.internal:host-gateway
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - 5968:8080
    volumes:
      - /home/jaumoso/selfhosted/n8n/searxng-settings:/etc/searxng
      - /mnt/externaldisk0/searxng:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=https://searxng.jaumoso.ovh
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 1MB
        max-file: "1"
  redis:
    image: redis:alpine
    container_name: n8n-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy
      allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - /mnt/externaldisk0/n8n/redis:/data
networks: {}
