services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: 1000:1000
    ports:
      - 3000:3000
    volumes:
      - /mnt/externaldisk0/grafana/grafana-data:/var/lib/grafana
      #- /mnt/externaldisk0/grafana/provisioning:/etc/grafana/provisioning
      - /home/jaumoso/selfhosted/grafana/provisionings:/etc/grafana/provisionings
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - prometheus
      - loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      #- /mnt/externaldisk0/loki:/etc/loki
      - /home/jaumoso/selfhosted/grafana/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki
    restart: unless-stopped
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      # Carpeta de logs del sistema
      - /var/log:/var/log
      # Persistencia de positions
      - /home/jaumoso/selfhosted/grafana/positions:/var/lib/promtail
      #- /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Configuracion de promtail
      - /home/jaumoso/selfhosted/grafana/promtail-config.yaml:/etc/promtail/config.yml
      # Sock de docker para logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: unless-stopped
networks:
  loki: null
  prometheus:
    external: true
