services:
  bichon:
    container_name: bichon
    image: rustmailer/bichon:latest
    ports:
      - 15630:15630
    volumes:
      - /mnt/externaldisk0/bichon:/data
    environment:
      - BICHON_LOG_LEVEL=warn
      - BICHON_ROOT_DIR=/data
      - BICHON_CORS_ORIGINS=https://bichon.jaumoso.ovh
    restart: unless-stopped
networks: {}
