services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/jaumoso/selfhosted/bazarr/config:/config
      #- /mnt/externaldisk0/media/movies
      #- /mnt/externaldisk0/media/series:/tv
      - /mnt/externaldisk0/media:/media
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - jellyfin
networks:
  jellyfin:
    external: true
