services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    user: 1000:1000
    ports:
      - 5030:5030
      #      - 5031:5031
      - 50300:50300
      #environment:
      #- SLSKD_REMOTE_CONFIGURATION=false
      #- SLSKD_SHARED_DIR=/music
    volumes:
      - /mnt/externaldisk0/slskd:/app:rw
      - /mnt/externaldisk0/media/music:/data/share:rw
      - /mnt/externaldisk0/media/downloads/music:/data/downloads:rw
      - /mnt/externaldisk0/slskd/incomplete:/data/incomplete:rw
    restart: unless-stopped
networks: {}
